version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    # TODO: Remove the target-branch
    target-branch: 'develop'
    schedule:
      interval: 'daily'
    reviewers:
      - 'austintoddj'
    labels:
      - 'npm'
      - 'dependencies'
    commit-message:
      prefix: 'chore(deps)'
