import {
  IconArrowNarrowRight,
  IconArticle,
  IconBrandFacebook,
  IconBrandInstagram,
  IconBrandLinkedin,
  IconBrandTiktok,
  IconBrandX,
  IconBuilding,
  IconBulb,
  IconCalendar,
  IconCertificate,
  IconChartPie,
  IconCheck,
  IconChevronDown,
  IconChevronRight,
  IconChevronsRight,
  IconClock,
  IconCoffee,
  IconCurrencyDollar,
  IconHelpCircle,
  IconHome,
  IconLifebuoy,
  IconListCheck,
  IconMail,
  IconMapPin,
  IconMeat,
  IconMessages,
  IconMoodKid,
  IconPhone,
  IconPhoto,
  IconPin,
  IconPlayerPlayFilled,
  IconPlus,
  IconSend,
  IconStarFilled,
  IconUser,
  IconUsers,
  IconVirus
} from '@tabler/icons-react'

const iconOptions = {
  calendar: IconCalendar,
  dollar: IconCurrencyDollar,
  user: IconUser,
  bulb: IconBulb,
  ratio: IconChartPie,
  home: IconHome,
  send: IconSend,
  mail: IconMail,
  pin: IconPin,
  building: IconBuilding,
  phone: IconPhone,
  messages: IconMessages,
  listCheck: IconListCheck,
  meat: IconMeat,
  virus: IconVirus,
  photo: IconPhoto,
  arrowNarrowRight: IconArrowNarrowRight,
  chevronsRight: IconChevronsRight,
  chevronRight: IconChevronRight,
  mapPin: IconMapPin,
  moodKid: IconMoodKid,
  clock: IconClock,
  users: IconUsers,
  playFilled: IconPlayerPlayFilled,
  starFilled: IconStarFilled,
  check: IconCheck,
  certificate: IconCertificate,
  coffee: IconCoffee,
  plus: IconPlus,
  chevronDown: IconChevronDown,
  instagram: IconBrandInstagram,
  facebook: IconBrandFacebook,
  x: IconBrandX,
  linkedin: IconBrandLinkedin,
  tiktok: IconBrandTiktok,
  lifeBuoy: IconLifebuoy,
  help: IconHelpCircle,
  article: IconArticle
}

export const Icon = ({ icon, className = '', stroke = 1.5 }) => {
  const iconName = icon || Object.keys(iconOptions)[0]
  const IconSVG = iconOptions[iconName]

  return <IconSVG className={`${className}`} stroke={stroke} />
}
