name: E2E — Smoke (PR)

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: e2e-smoke-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  e2e:
    name: e2e/smoke
    uses: ./.github/workflows/setup-runner.yml
    with:
      node-version: 18
      install-playwright: true
      run-command: npx start-server-and-test 'npm run dev' http://localhost:3000 "npx playwright test tests/e2e/smoke.spec.ts --project=chromium --reporter=html,junit"
      upload-artifact-path: ./playwright-report
      upload-artifact-name: e2e-smoke-report
    secrets:
      E2E_BASE_URL: ${{ secrets.E2E_BASE_URL }}

