name: E2E — Full

on:
  workflow_dispatch:
    inputs:
      base_url:
        description: 'URL to run E2E tests against (overrides secret)'
        required: false
        default: ''
  push:
    branches: [main]

concurrency:
  group: e2e-full-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  e2e:
    name: e2e/full
    uses: ./.github/workflows/setup-runner.yml
    with:
      node-version: 18
      install-playwright: true
      run-command: npx playwright test --reporter=html,junit
      upload-artifact-path: ./playwright-report
      upload-artifact-name: e2e-full-report
      base-url: ${{ github.event.inputs.base_url }}
    secrets:
      E2E_BASE_URL: ${{ secrets.E2E_BASE_URL }}
